### ISSUE TITLE
Add filters to widgets

### ISSUE THREAD

**Issue by buzkall** [andreaselia/filament-laravel-analytics#1]
Are you open to PRs?
I could PR a change to add the filament widget filter and merge all the widgets into one blade file.

<img width="864" alt="2022-12-17 at 12 25 10@2x" src="https://user-images.githubusercontent.com/5702/208239423-3251f7bc-aeba-44d4-8f81-e04924987945.png">

**Comment by andreaselia** [comment]
I'm open to PR's, but I'm not sure there should be a filter for each element, and rather a single filter that filters them all. What do you think?

**Comment by buzkall** [comment]
If there is a custom page only for the analytics widgets, sure, I'll go for a single filter. 
But being the general dashboard, there could be other widgets and a single filter might be confusing or incorrect.

**Comment by andreaselia** [comment]
Sounds good, I'd be happy to accept a PR implementing it.

**Comment by andreaselia** [comment]
I guess this is resolved in #2.
